name = "dashboard"
main = "worker/index.js"
compatibility_date = "2026-03-24"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "dashboard-db"
database_id = "c24d871e-8d3f-4d78-965b-b073270a0916"
migrations_dir = "migrations"

[triggers]
crons = [
  "*/5 * * * *",
  "7,37 * * * *",
  "12 * * * *",
  "22 3 * * *",
  "42 3 * * *"
]
